services:
- postgresql
before_script:
 - psql -c 'create database vedasprodutoweb;' -U postgres
 - psql -U postgres -d teste -f src/main/java/Banco/scriptTabelas.sql                 

language: java
jdk:
- oraclejdk8
script: mvn clean verify -DskipTests=false -DskipITs=false -DskipSTs=false