services:
- postgresql

cache:
  directories:
  - .autoconf
  - $HOME/.m2

addons:
  sonarcloud:
    organization: "felipemiotto-github"
before_script:
- psql -c 'create database vendasprodutoweb;' -U postgres
- psql -U postgres -d vendasprodutoweb -f src/main/java/Banco/scriptTabelas.sql                 

language: java
jdk:
- oraclejdk8
script:
- mvn clean verify -DskipTests=false -DskipITs=false -DskipSTs=false
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
